name: deploy on vm
on:
  push:
    branches:
      - demo23 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name:  login on server
        run: |
          mkdir .ssh
          cd .ssh
          echo "${{ secrets.shiv }}" > shiv
          ls -ltr
          chmod 600 shiv
          ls -ltr
          pwd
          cat shiv
          ssh -i shiv -o StrictHostKeyChecking=no yashjain200502@35.246.38.170 << 'EOF'
            pwd

            if [ -d "bit1" ]; then
              echo "Directory bit1 already exists. Pulling latest changes."
              cd bit1
              git pull origin demo23
            else
              echo "Directory bit1 does not exist. Cloning repository."
              git clone https://github.com/shivR30240/bit bit1
              cd bit1
            fi
            git checkout demo23
           
            docker rm flask | true
            docker build -t img .
            docker run --name flask -d -p 5000:5000 img


          EOF

     