name: deploy on vm
on:
  push:
    branches:
      - demo23 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name:  login on server
        run: |
          mkdir .ssh
          cd .ssh
          echo "${{ secrets.shiv }}" > shiv
          ls -ltr
          chmod 600 shiv
          ls -ltr
          pwd
          cat shiv
          ssh -i shiv -o StrictHostKeyChecking=no yashjain200502@35.246.38.170 << 'EOF'
            pwd
            if [ -d "bit" ]; then
              echo "Directory bit already exists. Pulling latest changes."
              cd bit
              git pull 
            else
              echo "Directory bit does not exist. Cloning repository."
              git clone https://github.com/shivR30240/bit
              cd bit
            fi
            git checkout demo23
            if [ -d "venv" ]; then
              echo "Virtual environment already exists."
            else
              echo "Creating virtual environment."
              python3 -m venv venv
            fi

            source venv/bin/activate
            pip install -r requirements.txt
            flask --app app run --host=0.0.0.0 --port=5000 


          EOF

     